# Generated by Django 3.0.1 on 2020-02-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Social_Media_Links',
            new_name='SocialMediaLinks',
        ),
    ]
