# Generated by Django 3.0.1 on 2020-02-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200214_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='productItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('img1', models.FileField(blank=True, null=True, upload_to='')),
                ('img2', models.FileField(blank=True, null=True, upload_to='')),
                ('img3', models.FileField(blank=True, null=True, upload_to='')),
                ('img4', models.FileField(blank=True, null=True, upload_to='')),
                ('img5', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
